server:
  port: 1817
spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: org.gjt.mm.mysql.Driver
    slave:
      url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: org.gjt.mm.mysql.Driver
  application:
    name: dynamic-datasource

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.zgf.springcloud.domain
  # 默认位置，可不配置
#  mapper-locations: classpath*:/mapper/**/*.xml
