server:
  port: 1815
spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: org.gjt.mm.mysql.Driver
    slave:
      url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: org.gjt.mm.mysql.Driver
  application:
    name: basic-multi-datasource
